import { FlatCompat } from "@eslint/eslintrc";
import js from "@eslint/js";
import nx from "@nx/eslint-plugin";
import { dirname } from "path";
import { fileURLToPath } from "url";

import baseConfig from "../../eslint.config.mjs";

const compat = new FlatCompat({
  baseDirectory: dirname(fileURLToPath(import.meta.url)),
  recommendedConfig: js.configs.recommended,
});

const config = [
  ...baseConfig,
  ...nx.configs["flat/react-typescript"],
  ...compat.extends("next", "next/core-web-vitals"),
  {
    rules: {},
  },
  {
    files: ["**/*.*"],
    rules: {
      "@next/next/no-html-link-for-pages": "off",
      "react/display-name": "off",
    },
  },
  {
    files: ["**/*.ts", "**/*.tsx"],
    // Override or add rules here
    rules: {},
  },
  {
    files: ["**/*.js", "**/*.jsx"],
    // Override or add rules here
    rules: {},
  },
  {
    ignores: [
      "dist",
      "dev-dist",
      "build",
      ".history",
      ".next",
      // Regenerated by `next build` on every run; its triple-slash references
      // are Next's to write, not ours to satisfy.
      "next-env.d.ts",
      // Not JavaScript: ESLint's TypeScript parser chokes on Tailwind's
      // at-rules and on the binary favicon.
      "**/*.css",
      "**/*.ico",
      "**/*.json",
    ],
  },
];

export default config;
